# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(426, 508)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Asky_Logo_black_500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, 160, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.user_id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_id_input.setGeometry(QtCore.QRect(80, 250, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.user_id_input.setFont(font)
        self.user_id_input.setText("")
        self.user_id_input.setObjectName("user_id_input")
        self.user_login_button_input = QtWidgets.QPushButton(self.centralwidget)
        self.user_login_button_input.setGeometry(QtCore.QRect(78, 400, 275, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user_login_button_input.setFont(font)
        self.user_login_button_input.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.user_login_button_input.setObjectName("user_login_button_input")
        self.user_password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_password_input.setGeometry(QtCore.QRect(80, 320, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.user_password_input.setFont(font)
        self.user_password_input.setText("")
        self.user_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password_input.setObjectName("user_password_input")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(110, -10, 201, 211))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setAutoFillBackground(False)
        self.logo.setStyleSheet("image : url(:/Images/Asky_Logo_black_500.png);\n"
"background:transparent")
        self.logo.setText("")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.id_error_label = QtWidgets.QLabel(self.centralwidget)
        self.id_error_label.setGeometry(QtCore.QRect(83, 290, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.id_error_label.setFont(font)
        self.id_error_label.setStyleSheet("color:red;")
        self.id_error_label.setText("")
        self.id_error_label.setObjectName("id_error_label")
        self.password_error_label = QtWidgets.QLabel(self.centralwidget)
        self.password_error_label.setGeometry(QtCore.QRect(83, 360, 261, 16))
        self.password_error_label.setStyleSheet("color:red;")
        self.password_error_label.setText("")
        self.password_error_label.setObjectName("password_error_label")
        self.forgot_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.forgot_password_button.setGeometry(QtCore.QRect(130, 450, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.forgot_password_button.setFont(font)
        self.forgot_password_button.setStyleSheet("color:grey;\n"
"background:transparent;")
        self.forgot_password_button.setObjectName("forgot_password_button")
        self.user_login_button_input.raise_()
        self.label.raise_()
        self.user_id_input.raise_()
        self.user_password_input.raise_()
        self.logo.raise_()
        self.id_error_label.raise_()
        self.password_error_label.raise_()
        self.forgot_password_button.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        LoginWindow.setTabOrder(self.user_id_input, self.user_password_input)
        LoginWindow.setTabOrder(self.user_password_input, self.user_login_button_input)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Asky Printer"))
        self.label.setText(_translate("LoginWindow", "PRINTERS"))
        self.user_id_input.setPlaceholderText(_translate("LoginWindow", "Email"))
        self.user_login_button_input.setText(_translate("LoginWindow", "Login"))
        self.user_password_input.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.forgot_password_button.setText(_translate("LoginWindow", "Forgot Password?"))
from . import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
