# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(229, 424)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Asky_Logo_black_500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(20, 380, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton {\n"
"    background-color:white;\n"
"    border-radius: 10px;\n"
"    color:black;\n"
"}")
        self.logout_button.setObjectName("logout_button")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(0, 10, 231, 141))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setAutoFillBackground(False)
        self.logo.setStyleSheet("image : url(:/Images/Asky_Logo_black_500.png);\n"
"background:transparent")
        self.logo.setText("")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.refresh_printer_list_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_printer_list_button.setGeometry(QtCore.QRect(20, 260, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refresh_printer_list_button.setFont(font)
        self.refresh_printer_list_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.refresh_printer_list_button.setObjectName("refresh_printer_list_button")
        self.heading_label = QtWidgets.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(-130, 140, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setStyleSheet("background:transparent;")
        self.heading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.connection_label = QtWidgets.QPushButton(self.centralwidget)
        self.connection_label.setGeometry(QtCore.QRect(20, 210, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.connection_label.setFont(font)
        self.connection_label.setStyleSheet("QPushButton {\n"
"    background-color:white;\n"
"    border-radius: 10px;\n"
"    color:black;\n"
"}")
        self.connection_label.setObjectName("connection_label")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(20, 320, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settings_button.setFont(font)
        self.settings_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.settings_button.setObjectName("settings_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Asky Printer"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
        self.refresh_printer_list_button.setText(_translate("MainWindow", "Refresh Printers List"))
        self.heading_label.setText(_translate("MainWindow", "PRINTERS"))
        self.connection_label.setText(_translate("MainWindow", "🟢 Connected to Server"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
from . import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
