# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printer_selection_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrinterSelectionWindow(object):
    def setupUi(self, PrinterSelectionWindow):
        PrinterSelectionWindow.setObjectName("PrinterSelectionWindow")
        PrinterSelectionWindow.resize(800, 719)
        PrinterSelectionWindow.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(PrinterSelectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_auto_network_printer_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_auto_network_printer_button.setGeometry(QtCore.QRect(100, 260, 190, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_auto_network_printer_button.setFont(font)
        self.add_auto_network_printer_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.add_auto_network_printer_button.setObjectName("add_auto_network_printer_button")
        self.network_printer_input = QtWidgets.QLineEdit(self.centralwidget)
        self.network_printer_input.setGeometry(QtCore.QRect(450, 190, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.network_printer_input.setFont(font)
        self.network_printer_input.setText("")
        self.network_printer_input.setObjectName("network_printer_input")
        self.auto_network_printers_combo = QtWidgets.QComboBox(self.centralwidget)
        self.auto_network_printers_combo.setGeometry(QtCore.QRect(70, 190, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.auto_network_printers_combo.setFont(font)
        self.auto_network_printers_combo.setPlaceholderText("")
        self.auto_network_printers_combo.setObjectName("auto_network_printers_combo")
        self.auto_network_printers_combo.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 140, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 140, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.printer_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.printer_list_widget.setGeometry(QtCore.QRect(70, 330, 661, 221))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.printer_list_widget.setFont(font)
        self.printer_list_widget.setStyleSheet("text-align:center;")
        self.printer_list_widget.setObjectName("printer_list_widget")
        self.remove_printer_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_printer_button.setGeometry(QtCore.QRect(260, 570, 275, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.remove_printer_button.setFont(font)
        self.remove_printer_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 119, 119);\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(255, 0, 0); /* Change the background on press */\n"
"}")
        self.remove_printer_button.setObjectName("remove_printer_button")
        self.network_printer_button = QtWidgets.QPushButton(self.centralwidget)
        self.network_printer_button.setGeometry(QtCore.QRect(490, 260, 190, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.network_printer_button.setFont(font)
        self.network_printer_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.network_printer_button.setObjectName("network_printer_button")
        self.confirm_config_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_config_button.setGeometry(QtCore.QRect(310, 620, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_config_button.setFont(font)
        self.confirm_config_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.confirm_config_button.setObjectName("confirm_config_button")
        self.heading_label = QtWidgets.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(140, 30, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        PrinterSelectionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PrinterSelectionWindow)
        QtCore.QMetaObject.connectSlotsByName(PrinterSelectionWindow)

    def retranslateUi(self, PrinterSelectionWindow):
        _translate = QtCore.QCoreApplication.translate
        PrinterSelectionWindow.setWindowTitle(_translate("PrinterSelectionWindow", "Printer Configuration"))
        self.add_auto_network_printer_button.setText(_translate("PrinterSelectionWindow", "Add Printer"))
        self.network_printer_input.setPlaceholderText(_translate("PrinterSelectionWindow", "Printer IP Address"))
        self.auto_network_printers_combo.setItemText(0, _translate("PrinterSelectionWindow", "--Select--"))
        self.label_2.setText(_translate("PrinterSelectionWindow", "Detected Network Printers"))
        self.label_3.setText(_translate("PrinterSelectionWindow", "Custom Network Printers"))
        self.remove_printer_button.setText(_translate("PrinterSelectionWindow", "Remove Selected Printer"))
        self.network_printer_button.setText(_translate("PrinterSelectionWindow", "Add Printer"))
        self.confirm_config_button.setText(_translate("PrinterSelectionWindow", "Confirm"))
        self.heading_label.setText(_translate("PrinterSelectionWindow", "PRINTER CONFIGURATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrinterSelectionWindow = QtWidgets.QMainWindow()
    ui = Ui_PrinterSelectionWindow()
    ui.setupUi(PrinterSelectionWindow)
    PrinterSelectionWindow.show()
    sys.exit(app.exec_())
