# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(210, 404)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.port_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.port_add_button.setGeometry(QtCore.QRect(120, 65, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.port_add_button.setFont(font)
        self.port_add_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.port_add_button.setObjectName("port_add_button")
        self.port_list_label = QtWidgets.QLabel(self.centralwidget)
        self.port_list_label.setGeometry(QtCore.QRect(24, 100, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.port_list_label.setFont(font)
        self.port_list_label.setStyleSheet("background:transparent;")
        self.port_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.port_list_label.setObjectName("port_list_label")
        self.port_remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.port_remove_button.setGeometry(QtCore.QRect(50, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.port_remove_button.setFont(font)
        self.port_remove_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 78, 78);\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:red; /* Change the background on press */\n"
"}")
        self.port_remove_button.setObjectName("port_remove_button")
        self.new_port_input = QtWidgets.QLineEdit(self.centralwidget)
        self.new_port_input.setGeometry(QtCore.QRect(30, 66, 71, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.new_port_input.setFont(font)
        self.new_port_input.setText("")
        self.new_port_input.setObjectName("new_port_input")
        self.heading_label = QtWidgets.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(10, -10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.done_button = QtWidgets.QPushButton(self.centralwidget)
        self.done_button.setGeometry(QtCore.QRect(50, 320, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.done_button.setFont(font)
        self.done_button.setStyleSheet("QPushButton {\n"
"    background-color:#3282fb;\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(129, 129, 129); /* Thicker red border when pressed */\n"
"     background-color:rgb(44, 115, 221); /* Change the background on press */\n"
"}")
        self.done_button.setObjectName("done_button")
        self.devider = QtWidgets.QFrame(self.centralwidget)
        self.devider.setGeometry(QtCore.QRect(14, 40, 180, 3))
        self.devider.setFrameShape(QtWidgets.QFrame.HLine)
        self.devider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.devider.setObjectName("devider")
        self.port_list = QtWidgets.QListWidget(self.centralwidget)
        self.port_list.setGeometry(QtCore.QRect(20, 160, 161, 81))
        self.port_list.setObjectName("port_list")
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 210, 21))
        self.menubar.setObjectName("menubar")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.port_add_button.setText(_translate("SettingsWindow", "Add"))
        self.port_list_label.setText(_translate("SettingsWindow", "SCANNING PORTS"))
        self.port_remove_button.setText(_translate("SettingsWindow", "Remove"))
        self.new_port_input.setPlaceholderText(_translate("SettingsWindow", "Port"))
        self.heading_label.setText(_translate("SettingsWindow", "SETTINGS"))
        self.done_button.setText(_translate("SettingsWindow", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
